### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by ericgaspar**

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ghost** [comment]
!testme

**Comment by ghost** [comment]
@ericgaspar I think the app is good to go, it is ready for production deployment after the push to master.


[Complete-0.log](https://github.com/YunoHost-Apps/abantecart_ynh/files/7877189/Complete-0.log)
summary

**Comment by ericgaspar** [comment]
>  I think the app is good to go, it is ready for production deployment after the push to master.

For now the Upgrade script is an empty shell...
The app should be upgradable like the other apps. (Doing the upgrade by hand is not really in the spirit of the YunoHost philosophy...)
Edit: Also the CI is expecting a working upgrade script. Otherwise it gets a level 2 and it's flagged as not working in the catalog...

**Comment by ghost** [comment]
The upgrade script script is really the problem. I guess making of the SQL script from source upgrade package maybe a workaround for it.

**Comment by ghost** [comment]
I am not sure if this method works. Please review.

**Comment by ericgaspar** [comment]
Did you test it? Is it working?

**Comment by ghost** [comment]
This SQL file is currently served as an example for future references. I'm currently testing it out. If not, I will revert the changes.

**Comment by myprivacyisgone** [comment]
!testme

**Comment by myprivacyisgone** [comment]
It seems to be working.. But I'm not sure `ynh_mysql_execute_file_as_root` ran in the correct way.
[Complete-0.log](https://github.com/YunoHost-Apps/abantecart_ynh/files/7886713/Complete-0.log)
. 
summary

**Comment by myprivacyisgone** [comment]
Upgrade works!

[Complete-0.log](https://github.com/YunoHost-Apps/abantecart_ynh/files/7889597/Complete-0.log)
summary

**Comment by ghost** [comment]
!testme

**Comment by myprivacyisgone** [comment]
- The install script works after src_version variable was added.

[Complete-0.log](https://github.com/YunoHost-Apps/abantecart_ynh/files/7889920/Complete-0.log)
summary

**Comment by myprivacyisgone** [comment]
- Upgrade script works after commit 2434dd6f00486aa3fb891fb115703fb54353bb68
Local test results:
summary
[Complete-0.log](https://github.com/YunoHost-Apps/abantecart_ynh/files/7889938/Complete-0.log)

**Comment by ghost** [comment]
Overall, the script works. Please review.

**Comment by myprivacyisgone** [comment]
!testme

**Comment by ghost** [comment]
!testme

**Pull request merged**
