### PR TITLE
Package Rewrite

### PR DESCRIPTION
**Pull request by ghost**
- Package works now except Upgrade and Change_path haven't implemented
- Nginx config works but insecure

### CODE REVIEW

**Comment by ghost** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Comment by ericgaspar** [comment]
@myprivacyisgone Thanks for the work! Do you want to maintain this app?

**Comment by ghost** [comment]
> @myprivacyisgone Thanks for the work! Do you want to maintain this app?

Yes, I would like to.

**Comment by ericgaspar** [comment]
Cool! You should have write access now

**Pull request merged**
